export type PortHistory = {
  summary: string;
  more: string;
  wikiTitle: string;
  officialSource?: { label: string; url: string };
};

export const portHistories: Record<string, PortHistory> = {
  nassau: {
    summary: "Nassau began as a 17th-century British settlement on New Providence and was renamed in 1695 after William III of the House of Nassau. Its sheltered harbour later became a notorious pirate base before Britain reasserted control in 1718. The forts, old streets and Junkanoo traditions around today’s capital still carry those layers of colonial, African and maritime history.",
    more: "The settlement first known as Charles Town was repeatedly attacked during European wars in the Caribbean and, for a time, weak colonial government allowed privateers and pirates to dominate New Providence. Governor Woodes Rogers arrived in 1718 with a royal mandate to restore order, beginning the period often described as the end of Nassau’s ‘pirate republic’. Loyalist migration after the American Revolution, emancipation, Atlantic trade and later tourism all reshaped the city. For a visitor today, places such as Fort Fincastle, Fort Charlotte, the Queen’s Staircase and the older neighbourhoods south of the waterfront make that history easier to read beyond the cruise terminal.",
    wikiTitle: "Nassau, Bahamas",
    officialSource: { label: "The Bahamas official tourism site", url: "https://www.bahamas.com/our-history" },
  },
  cozumel: {
    summary: "Cozumel was settled by the Maya and became an important pilgrimage island associated with Ixchel as well as a stop on Caribbean trade routes. Spanish expeditions reached the island in the early 16th century, while later upheaval on the Yucatán Peninsula helped repopulate San Miguel in the 19th century. Diving, reef tourism and cruise travel then transformed the island without erasing its Maya and fishing-community roots.",
    more: "Archaeological sites across Cozumel show occupation long before European contact, and San Gervasio preserves the island’s best-known surviving Maya remains. Juan de Grijalva’s expedition reached Cozumel in 1518, followed soon after by Hernán Cortés, and disease and colonial disruption contributed to a severe population decline. During the Caste War of Yucatán, refugees settled on the island and San Miguel was formally recognised in 1849. The local municipality records Cozumel as an early tourism pioneer in Quintana Roo and the state’s first port to receive a cruise ship in 1960, a turning point that helps explain the island’s modern waterfront economy.",
    wikiTitle: "Cozumel",
    officialSource: { label: "Municipality of Cozumel", url: "https://cozumel.gob.mx/nuestro-municipio/" },
  },
  roatan: {
    summary: "Roatán’s history is a mix of Indigenous settlement, centuries of Spanish-British rivalry and the growth of Afro-Caribbean and Garifuna communities. Its protected bays attracted sailors, traders and pirates, while 19th-century migration from the Cayman Islands helped shape the English-speaking island culture still visible today. Tourism and diving arrived much later, built around the same reef and coastal geography that had always defined life here.",
    more: "Before European colonisation, the Bay Islands were inhabited by Indigenous peoples connected to cultures on the Honduran mainland. From the 16th through the 18th centuries, Roatán repeatedly changed hands or influence as Britain and Spain competed across the western Caribbean, and its coves became useful to privateers and other seafarers. In the 1800s, settlers and formerly enslaved people from the Cayman Islands became an important part of the island population, while Garifuna settlement at Punta Gorda added another enduring cultural strand. Britain briefly claimed the Bay Islands as a colony before they were formally returned to Honduras. In the late 20th century, diving and resort tourism expanded rapidly around the Mesoamerican Barrier Reef, bringing new investment while making marine conservation increasingly important.",
    wikiTitle: "Roatán",
  },
  "costa-maya": {
    summary: "Costa Maya is not an old colonial port but a modern cruise gateway on a coast whose deeper history is Maya and maritime. Nearby Mahahual remained a small fishing community for much of the 20th century, while archaeological sites such as Chacchoben connect the port call to a much older civilisation. The purpose-built cruise pier accelerated development at the end of the 20th century and changed the local economy dramatically.",
    more: "The southern Quintana Roo coast was historically far less urbanised than the resort corridor around Cancún and Playa del Carmen, although Maya communities and trade networks long predated modern tourism. Mahahual developed as a fishing village beside the Caribbean and the offshore reef system. Construction of a large cruise facility created what is now marketed as Costa Maya, placing the region within major western-Caribbean itineraries. Hurricane Dean badly damaged the port in 2007, and cruise operations resumed after reconstruction. That contrast between a new cruise complex, an older fishing village and ancient sites inland is the key to understanding the destination.",
    wikiTitle: "Costa Maya",
  },
  "san-juan": {
    summary: "San Juan was founded by the Spanish in 1521 and became one of the most important fortified ports in the Caribbean. Massive walls and forts protected the entrance to San Juan Bay and helped the city serve Spain’s Atlantic empire for centuries. Today Old San Juan remains the historic core, while the wider capital has grown into Puerto Rico’s cultural and commercial centre.",
    more: "The settlement moved from the earlier site of Caparra to the small islet that now contains Old San Juan, where the harbour was easier to defend. Spain built and expanded fortifications including El Morro and San Cristóbal as rival European powers contested Caribbean shipping routes. The city remained under Spanish rule until Puerto Rico passed to the United States in 1898 after the Spanish-American War. In the 20th century, urban growth spread well beyond the old walls, but the colonial street plan, forts and civic buildings survived. Puerto Rico’s tourism authority describes San Juan as the island’s centre of history and culture, and that mix of old-world fabric with a modern Caribbean capital is exactly what cruise visitors encounter.",
    wikiTitle: "San Juan, Puerto Rico",
    officialSource: { label: "Discover Puerto Rico", url: "https://www.discoverpuertorico.com/regions/san-juan" },
  },
  "st-thomas": {
    summary: "St. Thomas became a Danish Caribbean colony in the 17th century, with Charlotte Amalie developing into a busy free port and trading centre. The island’s history is inseparable from slavery, Atlantic commerce and the movement of people through one of the region’s best natural harbours. The United States purchased the Danish West Indies in 1917, and the island later evolved into a major tourism and cruise destination.",
    more: "The Danish West India Company established control over St. Thomas in the 1600s, and the harbour encouraged international trade as well as privateering. Enslaved Africans formed the labour base of the colonial economy until emancipation in the Danish West Indies in 1848. Charlotte Amalie’s warehouses, stair streets, churches and forts still reflect its role as a commercial entrepôt. After the United States acquired St. Thomas, St. John and St. Croix from Denmark in 1917, military and commercial connections to the mainland increased. Modern cruise development now dominates parts of the waterfront, but historic Charlotte Amalie remains close enough to reveal the older mercantile city.",
    wikiTitle: "Saint Thomas, U.S. Virgin Islands",
  },
  "st-maarten": {
    summary: "The island of Saint Martin has been shared by French and Dutch administrations since the 17th century, giving a small island an unusually layered political identity. Philipsburg was established on the Dutch side in the 18th century between Great Bay and the salt pond. Salt, trade and later duty-free commerce shaped the town before tourism became the dominant economic force after the mid-20th century.",
    more: "Indigenous settlement long preceded European claims, but the island became a contested Caribbean possession after Spanish, Dutch and French activity in the 1600s. The Dutch and French eventually formalised a division of the island that survives today. Philipsburg developed around the Great Salt Pond and harbour, with salt production and regional trade central to its growth. Sint Maarten’s designation as a duty-free port in 1939 and the expansion of air travel and tourism after the Second World War transformed the economy. The cruise terminal, Front Street and Great Bay now sit directly on top of that transition from salt-and-shipping town to international visitor hub.",
    wikiTitle: "Philipsburg, Sint Maarten",
  },
  "grand-cayman": {
    summary: "Grand Cayman’s history is rooted in seafaring, turtling and small coastal settlements rather than plantation-scale colonial development. George Town grew into the islands’ administrative and commercial centre as maritime work connected Caymanians to the wider Caribbean and Atlantic. Tourism and financial services later reshaped the economy, while the island’s reef and seafaring culture remained central to its identity.",
    more: "Although Columbus sighted the Cayman Islands in 1503, permanent settlement came much later under British influence from Jamaica. Early Caymanians relied on fishing, turtling, shipbuilding and work aboard merchant vessels, creating a strong maritime tradition that still informs local culture. Britain formally administered the islands with Jamaica until Jamaican independence in 1962, when Cayman chose to remain a British Overseas Territory. George Town expanded with modern banking and tourism, and Seven Mile Beach became one of the Caribbean’s best-known resort areas. For cruise visitors, the tender harbour is a reminder that the town’s relationship with the sea predates the modern visitor economy by centuries.",
    wikiTitle: "Grand Cayman",
  },
  "puerto-plata": {
    summary: "Puerto Plata is one of the oldest Spanish-founded ports on Hispaniola and was an important maritime outlet in the early colonial period. The city was destroyed and resettled more than once, and much of its distinctive Victorian character dates from rebuilding after the Dominican Restoration War. Its historic centre, rum traditions and Atlantic setting now sit beside two major modern cruise terminals.",
    more: "Spanish settlement on the north coast began around the start of the 16th century, when Puerto Plata served as a commercial port for the colony of Hispaniola. The Spanish crown ordered the town destroyed in 1605 as part of efforts to curb illegal trade with foreign ships, and it was repopulated roughly a century later. Puerto Plata was again heavily damaged during the 1860s conflict that restored Dominican independence from Spain, after which the centre was rebuilt with the colourful timber and ironwork now associated with the city. Late-19th-century trade gave Puerto Plata renewed importance, while cable-car tourism, beach resorts and, more recently, Amber Cove and Taino Bay returned cruise travel to the centre of the local economy.",
    wikiTitle: "Puerto Plata",
  },
  "ocho-rios": {
    summary: "Ocho Rios grew from a small north-coast Jamaican settlement associated with fishing, agriculture and shipping into one of the island’s best-known resort towns. Its harbour once served exports such as bananas before tourism changed the waterfront and local economy. Waterfalls, rivers and lush limestone landscapes then became the destination’s defining attractions.",
    more: "The town known locally as Ochi sits in St. Ann, a parish with deep Indigenous, colonial and plantation-era history. For much of its development, Ocho Rios was modest compared with Kingston or Montego Bay, but its harbour supported agricultural exports and coastal trade. Resort investment and cruise infrastructure expanded rapidly during the second half of the 20th century, turning the former fishing and shipping town into an international tourism centre. Dunn’s River Falls, the White River and nearby garden estates now drive much of the visitor experience, while local food, music and community life connect the resort landscape to broader Jamaican culture.",
    wikiTitle: "Ocho Rios",
  },
  bridgetown: {
    summary: "Bridgetown developed as the principal British colonial port of Barbados from the 17th century and became a major node in the Atlantic sugar economy. That prosperity depended heavily on enslaved African labour and on a fortified military system protecting Carlisle Bay and British trade. The historic town and Garrison are now UNESCO-listed, preserving an unusually complete record of that colonial urban landscape.",
    more: "English settlement began in the 1620s, and Bridgetown quickly grew around the Careenage as sugar transformed Barbados into one of Britain’s wealthiest Caribbean colonies. Ships, merchants, enslaved people, soldiers and goods moved through the port on a scale that gave the town regional importance. The nearby Garrison developed after 1650 into one of the strongest British military complexes in the Atlantic, while Bridgetown’s irregular street pattern retained traces of its early development. Emancipation, independence in 1966 and a growing tourism sector changed the city’s role, but the old port, Parliament area, synagogue, churches and Garrison continue to reveal the layers beneath the modern capital.",
    wikiTitle: "Bridgetown",
    officialSource: { label: "Visit Barbados", url: "https://www.visitbarbados.org/discover/unesco-world-heritage-site" },
  },
  castries: {
    summary: "Castries grew around one of Saint Lucia’s best natural harbours and became the island’s political and commercial centre. French and British rivalry repeatedly changed control of Saint Lucia, leaving traces in place names, architecture and military sites around the capital. Fires destroyed large parts of the city more than once, so today’s Castries combines surviving heritage with extensive 20th-century rebuilding.",
    more: "The harbour was known by the French as the Carénage before the town took the name Castries, honouring a French naval minister. Saint Lucia changed hands repeatedly between France and Britain during the colonial era, and the heights at Morne Fortune became strategically important in the struggle for the island. Major fires, including destructive 19th- and 20th-century events, reshaped much of the urban fabric. The Saint Lucia Tourism Authority still describes Castries as the island’s cultural and commercial heart, centred on its market and working harbour. Pointe Seraphine’s cruise facilities sit just north of this older city, making the transition from colonial port to modern capital unusually visible.",
    wikiTitle: "Castries",
    officialSource: { label: "Saint Lucia Tourism Authority", url: "https://stlucia.org/en/places-to-visit/castries/" },
  },
  barcelona: {
    summary: "Barcelona’s history stretches from an ancient settlement through the Roman colony of Barcino to a powerful medieval Mediterranean city. The Gothic Quarter preserves much of that Roman and medieval core, while 19th-century industrial growth produced the Eixample and the architecture now associated with Catalan Modernisme. The 1992 Olympics then accelerated a major waterfront transformation that helped reconnect the modern city with the sea.",
    more: "Roman Barcino was founded around the end of the 1st century BC, and fragments of its walls and street pattern survive in the old city. Barcelona later became an important centre within the Crown of Aragon, benefiting from Mediterranean commerce before periods of political conflict and decline. Industrialisation in the 19th century brought rapid population growth and the planned expansion beyond the old walls, creating the setting in which architects such as Gaudí and Domènech i Montaner worked. The Spanish Civil War and Franco era left deep political scars, while democratic transition restored Catalan institutions. Barcelona’s tourism office highlights the city’s layered Roman, medieval and modern history, much of which can be experienced on foot from the port-facing old town.",
    wikiTitle: "History of Barcelona",
    officialSource: { label: "Barcelona Tourism", url: "https://www.barcelonaturisme.com/wv3/en/page/43/history-of-barcelona.html" },
  },
  "civitavecchia-rome": {
    summary: "Civitavecchia has served as a maritime gateway to Rome since antiquity, when the emperor Trajan developed the harbour at Centumcellae. The port passed through papal control and repeated rebuilding before becoming one of Italy’s principal passenger harbours. Modern cruise visitors usually experience it less as a destination than as the long-distance launch point for Rome’s far older urban history.",
    more: "Trajan’s harbour works in the early 2nd century helped create a protected port north-west of Rome, and the settlement later endured conflict, raids and changing political control. During the Middle Ages and early modern period, Civitavecchia became part of the Papal States and its fortifications were strengthened. Bombing during the Second World War caused extensive destruction, after which the city and port were rebuilt. Today ferries, cargo traffic and cruise ships share a busy harbour whose strategic role has lasted nearly two millennia. The practical lesson for a cruise day is historical as much as logistical: Rome and Civitavecchia are linked, but they have always been distinct places separated by a substantial journey inland.",
    wikiTitle: "Civitavecchia",
  },
  "livorno-florence": {
    summary: "Livorno was deliberately developed by the Medici as a free port and commercial gateway for Tuscany, becoming one of the Mediterranean’s most cosmopolitan trading cities. Its tolerant port laws attracted merchants and communities from across Europe and the Mediterranean. Cruise passengers now use Livorno mainly as the gateway to Florence and Pisa, but the canals of Venezia Nuova still reveal the city’s own maritime past.",
    more: "Livorno expanded rapidly from the late 16th century under Medici rule, when the port was fortified and promoted through the Livornine laws offering commercial and religious privileges to newcomers. Jewish, Greek, Armenian, Dutch, English and other communities contributed to a diverse mercantile culture. The port remained economically important under later Tuscan rulers and after Italian unification. Heavy bombing in the Second World War damaged much of the historic centre, yet the Fortezza Vecchia, canals and surviving merchant architecture preserve the original harbour-city character. Florence’s Renaissance fame often overshadows Livorno, but the two cities were historically connected by the trade routes that made Tuscany prosperous.",
    wikiTitle: "Livorno",
  },
  naples: {
    summary: "Naples began as a Greek settlement and became one of the Mediterranean’s longest continuously inhabited major cities. Greek, Roman, Byzantine, Norman, Spanish and Bourbon rule all left marks on its dense historic centre and bay. The same volcanic landscape that shaped ancient Pompeii and Herculaneum now gives cruise visitors an unusually direct route from living city to archaeological past.",
    more: "The Greek city of Neapolis developed beside earlier settlements and later became an important Roman cultural centre. After the fall of Rome, Naples passed through Byzantine and southern Italian dynasties before becoming capital of powerful kingdoms under Angevin, Aragonese, Spanish and Bourbon rulers. Its churches, castles, palaces and street plan reflect those overlapping eras rather than a single architectural period. Unification brought Naples into the Kingdom of Italy in the 19th century, while war damage and post-war growth transformed the waterfront and suburbs. The historic centre remains UNESCO-listed, and the nearby ruins of Pompeii and Herculaneum make the Bay of Naples one of the world’s richest concentrations of urban and archaeological history.",
    wikiTitle: "History of Naples",
  },
  marseille: {
    summary: "Marseille was founded by Greek settlers as Massalia around 600 BC, making it one of Europe’s oldest continuously important port cities. Roman, medieval and modern trade repeatedly remade the city as people arrived from across the Mediterranean. Its identity today still comes from that port-city mix of migration, commerce, working neighbourhoods and an unusually strong relationship with the sea.",
    more: "Massalia grew into a successful Greek trading city before coming under Roman control in the 1st century BC. The harbour continued to matter through the medieval period, but Marseille expanded dramatically in the 19th century as French colonial trade connected it with North Africa and the wider Mediterranean. Waves of migration created the cosmopolitan city seen today, while wartime destruction and post-war reconstruction altered parts of the old centre. Marseille Tourism describes the city as one that has rebuilt on itself for more than 2,600 years, which is visible in the contrast between Le Panier, the Vieux-Port, 19th-century boulevards and contemporary landmarks such as Mucem.",
    wikiTitle: "History of Marseille",
    officialSource: { label: "Marseille Tourism", url: "https://www.marseille-tourisme.com/en/discover-marseille/culture-heritage/architecture/" },
  },
  "palma-de-mallorca": {
    summary: "Palma’s history layers Roman foundation, Islamic Medina Mayurqa and the Christian city created after the 13th-century conquest by James I of Aragon. The cathedral, Almudaina palace and old lanes around the harbour preserve that sequence particularly clearly. Later maritime trade, tourism and rapid 20th-century growth turned Palma into the capital of a globally known island destination.",
    more: "The Romans established Palma on a site with earlier Talaiotic settlement, and the city later passed through Vandal and Byzantine rule. Under Muslim control it became Medina Mayurqa, an important Balearic centre whose urban legacy still influences the old city. James I conquered Mallorca in 1229, after which Christian institutions reshaped the city and construction of the great Gothic cathedral began. Palma prospered through Mediterranean commerce but also experienced piracy, political change and economic cycles. In the modern era, the port expanded alongside mass tourism, yet the monumental waterfront still places the cathedral, palace and historic harbour within the same visual frame.",
    wikiTitle: "Palma de Mallorca",
  },
  "athens-piraeus": {
    summary: "Piraeus has been Athens’ maritime gateway since classical antiquity, when Themistocles developed it as the city’s main naval and commercial harbour. The Long Walls once linked port and city into a single defensive system, making control of Piraeus essential to Athenian power. Modern Piraeus was rebuilt as a working port in the 19th century and remains Greece’s largest passenger harbour.",
    more: "Ancient Piraeus was carefully planned around several natural harbours and became the naval base from which Athens projected power across the Aegean. Fortifications and the Long Walls tied it physically to Athens, while war and later invasions led to centuries of decline. The port revived after the creation of the modern Greek state, growing with shipping, industry and migration. Today its main harbour, Zea Marina and Mikrolimano sit beside archaeological remains, neoclassical buildings and dense urban neighbourhoods. Visit Greece describes Piraeus as both the gateway to the Aegean and a destination in its own right, although cruise itineraries naturally pull many visitors straight toward Athens and the Acropolis.",
    wikiTitle: "Piraeus",
    officialSource: { label: "Visit Greece", url: "https://www.visitgreece.gr/mainland/attica/piraeus/" },
  },
  santorini: {
    summary: "Santorini’s history is inseparable from its volcano, whose Bronze Age eruption transformed the island and buried the settlement at Akrotiri. Ancient Thera, Byzantine communities and centuries of Venetian and Ottoman rule followed on the reshaped caldera rim. Shipping, wine and later tourism then turned the dramatic volcanic landscape into the economic centre of the modern island.",
    more: "The Minoan-era settlement at Akrotiri was preserved beneath volcanic material after the enormous eruption of the second millennium BC, giving archaeologists an exceptional view of Aegean Bronze Age life. Spartan settlers later established Ancient Thera on Mesa Vouno, and the island passed through Roman and Byzantine periods before becoming part of the Venetian Duchy of the Archipelago. The name Santorini is linked to Saint Irene through Venetian usage. Maritime trade and wine supported prosperity in later centuries, but the 1956 earthquake caused severe damage and population loss. Santorini’s port authority notes that tourism’s rapid rise from the late 20th century brought the island back to global prominence, centred on the same caldera created by its ancient geology.",
    wikiTitle: "Santorini",
    officialSource: { label: "Santorini Port Authority guide", url: "https://www.santoriniports.gov.gr/en/santorini-guide" },
  },
  mykonos: {
    summary: "Mykonos was an ancient Cycladic island closely tied to nearby Delos, one of the Aegean’s major sacred centres. Venetian and Ottoman periods followed, and the island later played a role in the Greek War of Independence under Manto Mavrogenous. Shipping and trade declined in the 19th century, but tourism revived the economy and eventually made Mykonos one of Greece’s most internationally recognised islands.",
    more: "Ancient Mykonos served as a supply and transit point for Delos and moved through Roman and Byzantine rule before Venetian families took control after the Fourth Crusade. Ottoman influence followed, though the island retained forms of local self-government and developed a maritime trading culture. During the Greek Revolution, Manto Mavrogenous used her wealth and influence in support of independence and remains one of the island’s defining historical figures. Archaeological work on Delos helped attract early travellers, and international tourism accelerated after the mid-20th century. Visit Greece now presents Mykonos as a meeting point between cosmopolitan life and Cycladic character, but its windmills, chapels and harbour lanes predate the luxury image by centuries.",
    wikiTitle: "Mykonos",
    officialSource: { label: "Visit Greece", url: "https://www.visitgreece.gr/islands/cyclades/mykonos/" },
  },
  dubrovnik: {
    summary: "Dubrovnik grew into the maritime Republic of Ragusa, a small but wealthy Adriatic state that prospered through trade and diplomacy. Strong walls protected a city whose merchants connected the Balkans with Mediterranean ports for centuries. The republic ended during the Napoleonic era, but its carefully preserved urban fabric later became the core of a UNESCO World Heritage city.",
    more: "The medieval city developed from earlier coastal settlements and gradually built a sophisticated trading network supported by shipbuilding, consulates and careful diplomacy between larger powers. Ragusa’s institutions limited foreign domination and created a distinctive civic culture, while earthquakes—especially the devastating event of 1667—forced major rebuilding. French occupation ended the republic in the early 19th century, after which Dubrovnik passed into Habsburg rule and later Yugoslavia. The city was shelled during the Croatian War of Independence, and extensive restoration followed. Today the walls, Stradun, Rector’s Palace and harbour provide an unusually intact setting for understanding how a small maritime republic once competed across the Adriatic.",
    wikiTitle: "Dubrovnik",
  },
  split: {
    summary: "Split grew around the palace built for the Roman emperor Diocletian at the beginning of the 4th century. When nearby Salona declined, people moved inside the fortified palace and gradually turned an imperial residence into a living city. More than seventeen centuries later, homes, shops, churches and streets still occupy the Roman structure rather than merely surrounding it.",
    more: "The area had earlier Greek and Illyrian connections, but Diocletian’s vast retirement palace became the decisive urban framework. Refugees from Salona settled inside its walls in late antiquity, adapting ceremonial halls, gates and basements to everyday use. Split later moved between Byzantine, Croatian, Hungarian, Venetian, French and Austrian spheres before joining Yugoslavia and eventually independent Croatia. Venetian influence and later Habsburg urban expansion extended the city beyond the palace, while the Riva became its social waterfront. The UNESCO-listed historic centre is unusual because the Roman complex never became an isolated ruin: it continuously absorbed new generations of residents and functions.",
    wikiTitle: "Split, Croatia",
  },
  kotor: {
    summary: "Kotor is an old Adriatic port whose history stretches through Illyrian and Roman periods into a long medieval and Venetian era. Its position at the end of a deeply sheltered bay made it commercially valuable and strategically difficult to attack. The walls, churches and merchant houses of the old town now form part of a UNESCO-listed cultural landscape shaped by both sea and mountains.",
    more: "Roman and Byzantine influence preceded Kotor’s medieval development, when the town became part of shifting regional states and trading networks. From the 15th to the late 18th century it spent long periods under Venetian rule, during which many of the fortifications and architectural details visitors see today were strengthened or rebuilt. Earthquakes repeatedly damaged the town, most notably in 1667 and 1979, forcing cycles of reconstruction. Austrian, French and Yugoslav rule followed before Montenegro’s independence. Local tourism material emphasises the legacy of seafarers and traders, and the old town’s position beneath the San Giovanni fortifications makes that maritime-defensive history immediately visible from the cruise pier.",
    wikiTitle: "Kotor",
    officialSource: { label: "Kotor Tourism", url: "https://kotor.travel/" },
  },
  corfu: {
    summary: "Corfu’s position at the entrance to the Adriatic made it strategically important to Byzantine, Venetian, French and British powers. Venice controlled the island for centuries and built the formidable fortifications that helped keep it outside Ottoman rule. British administration ended in 1864 when Corfu and the other Ionian Islands joined the modern Greek state.",
    more: "Ancient Corcyra was a significant Greek polis and later became part of the Roman and Byzantine worlds. Medieval instability eventually gave way to long Venetian rule beginning in the late Middle Ages, during which the island served as a defensive outpost guarding approaches to the Adriatic. Repeated Ottoman sieges were repelled, strengthening Corfu’s reputation as one of the region’s most fortified places. French and then British control followed the fall of Venice, bringing new civic institutions and architecture. Corfu Town’s UNESCO-listed old centre, arcaded Liston, fortresses and churches therefore feel less like a typical Cycladic destination and more like a compact record of Adriatic-European rivalry.",
    wikiTitle: "Corfu",
  },
  "kusadasi-ephesus": {
    summary: "Kuşadası is a modern Aegean port whose cruise importance comes largely from its proximity to Ephesus, one of the great cities of the ancient Mediterranean. Ephesus flourished under Greek and especially Roman rule as a commercial, religious and administrative centre. As its harbour silted and regional power shifted, the ancient city declined while later settlements developed closer to today’s coast.",
    more: "Ephesus occupied a strategic position on Aegean trade routes and became famous for the Temple of Artemis, one of the Seven Wonders of the Ancient World. Under Roman rule it grew into the capital of the province of Asia, with monumental streets, baths, theatres and the Library of Celsus reflecting its wealth. The city also became important to early Christianity through traditions associated with St Paul, St John and the Virgin Mary. Progressive silting moved the shoreline away from the ancient harbour and contributed to decline. Kuşadası itself expanded around a later coastal harbour and today functions as the practical maritime gateway to the archaeological landscape inland.",
    wikiTitle: "Ephesus",
  },
  valletta: {
    summary: "Valletta was founded by the Knights of St John after their defence of Malta during the Great Siege of 1565. Built as a planned fortified capital on the Sciberras peninsula, it combined military engineering with churches, palaces and civic institutions. Its dense Baroque streets survived later British rule and heavy Second World War bombing to become one of Europe’s most concentrated historic capitals.",
    more: "Grand Master Jean Parisot de Valette gave his name to the new city, which was designed to strengthen control of Malta’s Grand Harbour after the Ottoman siege. The Knights brought architects, artists and resources from across Europe, creating St John’s Co-Cathedral, auberges for the different langues of the order and an elaborate defensive system. French occupation briefly interrupted the Knights’ rule in 1798, after which Malta became part of the British Empire. Valletta’s harbour was strategically important during both world wars and suffered major bombing damage. Independence and later restoration preserved the compact city, which UNESCO recognises for the extraordinary concentration of monuments within its fortifications.",
    wikiTitle: "Valletta",
  },
  "messina-taormina": {
    summary: "Messina has guarded the narrow strait between Sicily and mainland Italy since ancient times, making it a strategic harbour for trade and military movement. Earthquakes—especially the catastrophic 1908 disaster—destroyed much of the historic city, so modern Messina is largely a reconstruction. Nearby Taormina preserves a different story, with Greek and Roman remains set above the Ionian coast.",
    more: "Founded in antiquity as Zancle and later known as Messana, the city prospered because ships moving through the Strait of Messina naturally passed its harbour. Byzantine, Arab, Norman, Spanish and other rulers controlled Sicily across the centuries, while the port remained strategically important. The 1908 earthquake and tsunami killed tens of thousands and devastated the urban fabric, and Second World War bombing brought further destruction. Taormina, by contrast, survived with a celebrated ancient theatre and medieval streets on a hilltop south of the port. Cruise excursions often combine these two very different historical landscapes: a rebuilt working strait city and a preserved resort town rooted in antiquity.",
    wikiTitle: "Messina",
  },
  juneau: {
    summary: "Juneau grew rapidly after gold discoveries in the 1880s on land that had long been part of Tlingit territory. Mining transformed the Gastineau Channel waterfront and eventually helped the town become Alaska’s territorial and then state capital. Today government and tourism have replaced much of the mining economy, while glaciers, mountains and Tlingit cultural heritage remain central to the city’s identity.",
    more: "Tlingit communities used the region’s waterways and resources long before prospectors arrived. The discovery of gold near what became Juneau drew miners and companies, leading to large hard-rock operations around the channel and on nearby Douglas Island. The territorial government moved from Sitka to Juneau in the early 20th century, and the city retained capital status when Alaska became a state in 1959. As major mines closed, public administration, fishing and later cruise tourism became increasingly important. Mendenhall Glacier and the surrounding Tongass landscape now define many visitor experiences, but the city’s museums, clan houses and public art provide essential context for the Indigenous history that predates the gold-rush town.",
    wikiTitle: "Juneau, Alaska",
  },
  ketchikan: {
    summary: "Ketchikan developed around fishing, salmon canneries, timber and a sheltered waterfront in Southeast Alaska. The region is also part of the traditional homelands of Tlingit, Haida and Tsimshian peoples, whose art and clan histories long predate the modern town. Cruise tourism now dominates the summer waterfront, but Creek Street, canning history and totem collections still reflect older economic and cultural layers.",
    more: "Ketchikan’s non-Native settlement grew at the end of the 19th century as fishing and commercial activity expanded along Tongass Narrows. Salmon canneries made the town a major processing centre, while timber became important in the 20th century. At the same time, Native communities maintained complex cultural traditions visible in carved poles, regalia, stories and contemporary art. The closure of large industrial operations shifted the economy increasingly toward tourism, fishing and services. Totem Bight, Saxman and local museums help visitors understand that the poles are not generic decorations but part of specific clan histories, while Creek Street preserves the architecture of the town’s early commercial waterfront.",
    wikiTitle: "Ketchikan, Alaska",
  },
  skagway: {
    summary: "Skagway exploded into existence during the Klondike Gold Rush of 1897–98 as thousands of stampeders headed inland toward the Yukon. Its harbour, the White Pass trail and later the railway turned the small settlement into a critical gateway to the goldfields. Much of the compact downtown survives within Klondike Gold Rush National Historical Park, giving cruise visitors an unusually coherent view of a boomtown era.",
    more: "The area lies within the traditional homeland of the Tlingit, whose trade routes through the coastal mountains long predated the rush. When gold seekers arrived by ship, Skagway grew almost overnight with hotels, saloons, supply stores and a reputation for disorder. Construction of the White Pass & Yukon Route railway changed the logistics of the route and helped Skagway survive after the rush faded. Tourism itself began early, with visitors arriving by steamship while the gold rush was still underway. The restored buildings, railway depot and nearby Dyea landscape now preserve both the spectacular optimism and the human cost of that brief migration north.",
    wikiTitle: "Skagway, Alaska",
    officialSource: { label: "U.S. National Park Service", url: "https://www.nps.gov/klgo/learn/historyculture/index.htm" },
  },
  sitka: {
    summary: "Sitka is a place where Tlingit history, Russian colonial rule and the American period meet in the same small coastal city. The Kiks.ádi Tlingit resisted Russian expansion, while the Russian settlement of New Archangel later became the colonial capital of Alaska. In 1867 the formal transfer of Alaska from Russia to the United States took place here.",
    more: "The Tlingit people had deep ties to Sheet’ká long before Russian fur traders established a permanent base. Conflict culminated in the 1804 Battle of Sitka, after which the Russians developed New Archangel as the centre of their North American colony, supported by the fur trade and Russian Orthodox missions. The transfer ceremony for the Alaska Purchase occurred in Sitka in 1867, and the town initially remained the American territorial capital before that role moved to Juneau. Sitka National Historical Park now interprets the Kiks.ádi fort site, Russian period and Native cultural traditions, while the modern visitor bureau emphasises a living Tlingit culture rather than treating it only as history.",
    wikiTitle: "Sitka, Alaska",
    officialSource: { label: "National Park Service — Sitka", url: "https://www.nps.gov/sitk/learn/historyculture/index.htm" },
  },
  "icy-strait-point": {
    summary: "Icy Strait Point grew from a salmon cannery beside Hoonah, a Tlingit community with far older roots on Chichagof Island. The cannery began operating in the early 20th century and later closed as the fishing industry changed. Its historic buildings were eventually redeveloped as a cruise destination with strong local ownership and a focus on Tlingit culture and wildlife.",
    more: "Hoonah is home to the Huna Tlingit, whose relationship with the surrounding waters, forests and Glacier Bay region reaches back generations. Industrial salmon processing brought wage work and new infrastructure to the waterfront, and the cannery complex became an important part of local economic history. After operations declined, the site was preserved and adapted rather than demolished. Icy Strait Point’s modern cruise development therefore differs from many purpose-built ports: historic cannery structures remain part of the visitor experience, and the destination’s connection to Hoonah means cultural interpretation and local employment are central to its identity.",
    wikiTitle: "Icy Strait Point",
  },
  "cabo-san-lucas": {
    summary: "Cabo San Lucas developed from a remote fishing and maritime outpost into an international resort at the southern tip of the Baja California Peninsula. Commercial fishing, especially tuna, supported much of its early 20th-century growth before road and air links opened the region to large-scale tourism. The Arch at Land’s End became the visual symbol of a destination built where the Pacific meets the Gulf of California.",
    more: "Indigenous peoples inhabited the southern peninsula long before Spanish exploration reached the area, but permanent colonial settlement remained limited compared with mainland Mexico. The modern town’s economy grew around fishing and a tuna cannery, with sport fishing later attracting visitors from the United States. Tourism accelerated in the second half of the 20th century as the Transpeninsular Highway, airport access and resort investment transformed Los Cabos. Cabo San Lucas retained a working marina even as hotels spread along the coast. Cruise ships still tender offshore, so the harbour arrival gives visitors a direct view of the town’s transition from fishing port to resort centre.",
    wikiTitle: "Cabo San Lucas",
  },
  "puerto-vallarta": {
    summary: "Puerto Vallarta began as a small Pacific settlement supporting mining communities in the Sierra Madre and later developed around fishing, agriculture and coastal trade. International attention increased dramatically in the 1960s, when film production and new air links introduced the town to a wider tourism market. Despite rapid resort growth, the Malecón, church and older streets around the Río Cuale preserve the scale of the earlier town.",
    more: "The settlement was known as Las Peñas before taking the name Puerto Vallarta in the early 20th century. Its harbour served regional mining and agricultural interests, while the surrounding bay supported fishing villages rather than large urban development. The filming of The Night of the Iguana near Mismaloya in the 1960s brought global publicity, and government investment in roads, airport infrastructure and utilities followed. Tourism then expanded north and south along Banderas Bay. The modern cruise terminal sits away from the historic centre, making the short journey to the Malecón a visible passage between contemporary resort infrastructure and the older Pacific port town.",
    wikiTitle: "Puerto Vallarta",
  },
  "cartagena-colombia": {
    summary: "Cartagena was founded by the Spanish in 1533 and became one of the empire’s most important fortified ports in the Americas. Gold, silver, enslaved Africans and other goods moved through the harbour, making the city wealthy and repeatedly vulnerable to attack. Its walls, bastions and colonial streets survive alongside strong Afro-Caribbean traditions and a modern Colombian port economy.",
    more: "The bay’s strategic position made Cartagena central to Spain’s Caribbean trade and to the forced movement of enslaved Africans into northern South America. Repeated attacks by privateers and rival powers led to a vast defensive system including the city walls and Castillo San Felipe de Barajas. Cartagena later became an important centre in the independence struggle from Spain and endured siege and economic decline before recovering as a regional port. The 20th century brought industrial growth and tourism, while neighbourhoods such as Getsemaní retained strong local identities. The contrast between cruise terminals, working docks, colonial fortifications and contemporary street life makes Cartagena’s history unusually visible in a single port call.",
    wikiTitle: "Cartagena, Colombia",
  },
  copenhagen: {
    summary: "Copenhagen grew from a medieval harbour settlement into Denmark’s capital and the centre of a powerful Baltic kingdom. Trade, royal building projects, fires and wars repeatedly reshaped the city, while Nyhavn and the old waterfront preserve its maritime character. Modern Copenhagen layers royal palaces and merchant districts with 19th- and 20th-century urban design.",
    more: "The settlement expanded around a strategic crossing between Zealand and Scania and gained importance under the Danish crown during the Middle Ages. Copenhagen became the royal capital and a major base for Baltic commerce, but fires in 1728 and 1795 and British bombardment in 1807 destroyed large areas, leading to repeated rebuilding. The removal of old fortifications in the 19th century allowed the city to expand beyond its historic core. Port industry later moved outward, freeing central harbour districts for new public and residential uses. For cruise visitors, Nyhavn, Christiansborg, Rosenborg and the harbourfront together show how a working royal capital evolved from its maritime origins.",
    wikiTitle: "History of Copenhagen",
  },
  stockholm: {
    summary: "Stockholm developed across islands at the meeting point of Lake Mälaren and the Baltic, a strategic position for medieval trade and defence. Gamla Stan became the political heart of the Swedish kingdom, while later naval and imperial ambitions reshaped the waterfront. The preserved Vasa warship offers one of the most vivid surviving objects from Sweden’s 17th-century great-power era.",
    more: "Stockholm’s medieval growth was closely tied to control of trade moving between the interior and the Baltic Sea. The city became the royal and administrative centre of Sweden and expanded beyond Gamla Stan as the kingdom’s economy and military power grew. Fire, industrialisation and 19th-century planning altered many neighbourhoods, but the old town retained its narrow street pattern and royal institutions. In the 20th century, Stockholm modernised rapidly while protecting substantial historic areas and developing museums across Djurgården. Cruise arrivals through the archipelago reinforce the geography that made Stockholm important in the first place: the city is inseparable from the waterways surrounding it.",
    wikiTitle: "History of Stockholm",
  },
  tallinn: {
    summary: "Tallinn became one of the Baltic’s important Hanseatic trading cities, linking northern European merchants with routes eastward. Its medieval walls, towers, guild houses and upper-town fortress survived to an unusual degree despite later Danish, Teutonic, Swedish and Russian rule. Estonia’s independence, Soviet occupation and restored independence in 1991 added modern political layers to the remarkably intact old town.",
    more: "A fortified settlement existed on Toompea long before the German and Danish crusading period, but medieval Reval grew especially through membership in the Hanseatic League. German-speaking merchants and guilds shaped the lower town while rulers changed above them, creating the distinctive division between Toompea and the commercial streets below. Swedish and then Russian imperial rule followed, and the city industrialised as a Baltic port. Estonia first declared independence in 1918, lost it during the Second World War and Soviet occupation, and restored it in 1991. The UNESCO-listed old town now gives cruise visitors one of Europe’s clearest surviving examples of a medieval trading city.",
    wikiTitle: "History of Tallinn",
  },
  bergen: {
    summary: "Bergen was a medieval royal centre and later one of the most important Hanseatic trading ports in northern Europe. German merchants dominated the Bryggen waterfront trade in stockfish for centuries, leaving the timber warehouses that define the harbour today. Fires repeatedly rebuilt the city, but the relationship between mountains, harbour and trade remained constant.",
    more: "Founded in the Middle Ages, Bergen became a royal seat and Norway’s largest city for centuries. From the late medieval period, Hanseatic merchants established a powerful trading community at Bryggen, exchanging northern Norwegian stockfish for grain and imported goods. Repeated fires destroyed large sections of the wooden city, so the surviving Bryggen buildings reflect cycles of reconstruction rather than untouched medieval fabric. Bergen’s role shifted with modern shipping, industry and eventually tourism, while the port remained active. The Fish Market, Bryggen and Fløibanen all sit within a compact landscape that still explains why this sheltered harbour became western Norway’s historic gateway.",
    wikiTitle: "History of Bergen",
  },
  geiranger: {
    summary: "Geiranger is a small fjord community whose history was shaped by isolated farms, seasonal agriculture and travel by water through one of Norway’s most dramatic landscapes. Tourism began well before the modern cruise era as 19th-century travellers came to see waterfalls and steep mountain farms. The village now sits within the UNESCO-listed West Norwegian Fjords landscape, where visitor pressure and heritage protection are tightly connected.",
    more: "For generations, people farmed narrow shelves above the fjord and relied on boats for transport through terrain that made overland travel difficult. Romantic-era travellers and early cruise ships brought a new economy to Geiranger in the 19th and early 20th centuries, and roads to viewpoints such as Ørnesvingen and Dalsnibba later expanded access. Abandoned farms on the cliffs still document how demanding settlement once was. UNESCO recognition of the West Norwegian Fjords reflects both geological significance and the cultural landscape created by human use. Modern Geiranger therefore has a much longer tourism history than its current cruise traffic might suggest.",
    wikiTitle: "Geiranger",
  },
  reykjavik: {
    summary: "Reykjavík grew from the area traditionally associated with Iceland’s first permanent Norse settlement into the country’s capital and main harbour city. For centuries it remained small, but trade liberalisation, fishing and political centralisation drove rapid growth in the 19th and 20th centuries. The compact old harbour now sits beside a modern city whose identity remains tied to the sea, geothermal energy and Iceland’s settlement history.",
    more: "According to Icelandic tradition, Ingólfur Arnarson established a settlement in the Reykjavík area in the late 9th century. The community remained modest for centuries under Norwegian and then Danish rule, while nearby farms and fishing supported local life. Reykjavík received trading privileges in the 18th century and gradually became the centre of Icelandic administration, independence politics and commerce. Urban growth accelerated with mechanised fishing, improved harbour facilities and the Second World War, when Allied forces were stationed in Iceland. After the republic was founded in 1944, Reykjavík expanded into the national cultural and political centre. The old harbour and nearby museums provide the clearest cruise-day connection to that evolution.",
    wikiTitle: "History of Reykjavík",
  },
  belfast: {
    summary: "Belfast grew from a small settlement into a major industrial port during the 18th and 19th centuries, becoming famous for linen, engineering and shipbuilding. Harland and Wolff built RMS Titanic here, a legacy now central to the redeveloped waterfront. The city’s modern story also includes the partition of Ireland, decades of conflict known as the Troubles and a continuing peace process.",
    more: "Belfast’s location at the head of Belfast Lough supported trade, but industrialisation transformed the scale of the city. Linen production, ropeworks, heavy engineering and shipbuilding drew workers and investment, while sectarian and political divisions sharpened as Ireland’s constitutional future became contested. After partition in 1921, Belfast became the capital of Northern Ireland. The Troubles from the late 1960s to the 1998 Good Friday Agreement left a profound social and physical legacy that remains visible in murals, memorials and interface areas. The regenerated Titanic Quarter shows another side of that history: a working shipyard landscape adapted into museums, offices and visitor attractions.",
    wikiTitle: "History of Belfast",
  },
  "le-havre-paris": {
    summary: "Le Havre was founded in the early 16th century as a new French port at the mouth of the Seine and became a major Atlantic trading centre. Much of the city was destroyed during the Second World War and rebuilt under architect Auguste Perret in a distinctive modernist style now recognised by UNESCO. Cruise itineraries often treat Le Havre mainly as a gateway to Paris, but the port city’s own history is unusually visible in its reconstruction.",
    more: "King Francis I established the harbour in 1517 to strengthen French access to the Channel and Atlantic, and Le Havre later grew through trade with the Americas, including commerce bound up with colonialism and slavery. Industrialisation expanded docks and shipping in the 19th century. Heavy Allied bombing in 1944 destroyed much of the centre during the liberation of France. Auguste Perret’s post-war plan used reinforced concrete, broad avenues and carefully proportioned civic buildings to create a new urban core. That rebuilt centre, rather than an old medieval district, is the city’s principal heritage asset and explains why UNESCO lists Le Havre as an outstanding example of post-war planning.",
    wikiTitle: "Le Havre",
  },
  singapore: {
    summary: "Modern Singapore developed rapidly after the British established a trading port here in 1819, taking advantage of its position on the sea routes between the Indian Ocean and South China Sea. Migration from China, the Malay world, India and beyond created the diverse port society visible in today’s neighbourhoods. Japanese occupation, self-government and independence in 1965 then transformed the trading colony into a sovereign global city-state.",
    more: "The island had earlier Malay settlements and regional trading connections, but the British free-port policy introduced by Stamford Raffles accelerated population and commercial growth on an extraordinary scale. Singapore became part of the Straits Settlements and one of the British Empire’s key Asian ports, built on maritime trade and migrant labour. Japanese occupation during the Second World War shattered assumptions about colonial security. After a brief merger with Malaysia, Singapore became independent in 1965 and pursued export-led industrialisation, housing construction and major port expansion. The contrast between Chinatown, Kampong Glam, the civic district and Marina Bay compresses that transition from colonial entrepôt to modern metropolis into a remarkably small area.",
    wikiTitle: "History of Singapore",
  },
  "tokyo-yokohama": {
    summary: "Yokohama changed from a small settlement into one of Japan’s main international ports after the country opened to foreign trade in the 19th century. The new harbour became a gateway for Western technology, ideas and commerce during the Meiji era. Earthquake, war and post-war rebuilding reshaped the city, which today forms part of the vast Tokyo metropolitan region while retaining its own waterfront identity.",
    more: "The treaties ending Japan’s long period of limited foreign contact designated Yokohama as a treaty port in 1859, and foreign settlements, warehouses and consulates quickly appeared around the harbour. Silk exports and imported technology connected the city to global markets, while rail links tied it increasingly to Tokyo. The Great Kantō Earthquake of 1923 devastated both cities, and wartime bombing caused further destruction. Post-war reconstruction turned Yokohama into a major industrial and container port. The modern Minato Mirai district occupies former docklands, while areas such as Yamashita Park and the historic foreign quarter preserve traces of the city’s role as one of the principal doors through which modern Japan engaged the world.",
    wikiTitle: "History of Yokohama",
  },
  "kobe-kyoto": {
    summary: "Kobe became one of Japan’s major international ports after opening to foreign trade in the 19th century, while Kyoto inland preserves more than a millennium of imperial, religious and artistic history. The two cities therefore offer very different historical experiences from the same cruise call. Kobe itself was rebuilt after the devastating 1995 Great Hanshin earthquake and remains a major maritime and commercial centre.",
    more: "The port area around Kobe had long supported coastal trade, but the opening of Hyōgo/Kobe to foreign commerce in 1868 created an international settlement and accelerated industrial growth. Merchants, diplomats and missionaries introduced new architecture and institutions, some of which survive in the Kitano district. The 1995 earthquake killed thousands and destroyed large parts of the city, prompting extensive reconstruction and new disaster-preparedness planning. Kyoto, by contrast, served as the imperial capital from 794 until the 19th century and escaped much of the wartime destruction suffered by other Japanese cities. A cruise excursion inland therefore trades Kobe’s modern port history for Kyoto’s temples, gardens and historic neighbourhoods.",
    wikiTitle: "Kobe",
  },
  "hong-kong": {
    summary: "Hong Kong grew from a cluster of coastal communities into a major British colonial port after the mid-19th century. Its deep harbour and position on China trade routes drove rapid commercial growth and successive waves of migration. The 1997 handover to China created the Hong Kong Special Administrative Region, adding a new political chapter to a city still defined by its harbour.",
    more: "The region had a much longer Chinese history before Britain took control of Hong Kong Island in 1841–42, followed later by Kowloon and the leased New Territories. Victoria Harbour became the economic engine of a colonial entrepôt linking southern China with global shipping, finance and manufacturing. Japanese occupation during the Second World War caused severe hardship, while post-war refugee arrivals and industrialisation produced another period of dramatic growth. From the 1970s onward, finance and services replaced much manufacturing. Sovereignty transferred to the People’s Republic of China in 1997 under the ‘one country, two systems’ framework. The Star Ferry, Central, Kowloon waterfront and hillside districts all reflect the geography that made the harbour central to the city’s development.",
    wikiTitle: "History of Hong Kong",
  },
  phuket: {
    summary: "Phuket’s history was shaped first by tin mining and maritime trade long before beaches became its global image. Chinese, Malay, Thai and European commercial influences are visible in the Sino-Portuguese streets of Phuket Old Town. Tourism expanded dramatically from the late 20th century, turning the island into one of Thailand’s busiest resort destinations while the old trading centre remained inland from the beaches.",
    more: "The island occupied a useful position on routes through the Andaman Sea, and tin deposits drew merchants and workers from across the region. Chinese migration played a major role in the mining economy, and wealthy families built the shophouses and mansions now associated with Phuket Town. The island also entered Thai national memory through resistance to a Burmese attack in the 18th century. Roads, air travel and international beach tourism changed the economy in the second half of the 20th century, with Patong and other coastal areas developing rapidly. The 2004 Indian Ocean tsunami caused devastating loss along the west coast, followed by reconstruction and new attention to disaster preparedness.",
    wikiTitle: "Phuket province",
  },
  sydney: {
    summary: "Sydney Harbour has been home to Aboriginal peoples for tens of thousands of years, with Gadigal and neighbouring communities maintaining deep cultural connections to the land and water. Britain established a penal colony at Sydney Cove in 1788, beginning a colonial expansion that displaced Indigenous communities and created the core of modern Sydney. The harbour later became a global symbol through the bridge and Opera House, both built on a much older cultural landscape.",
    more: "The Eora peoples lived around the harbour in complex communities with their own languages, trade and seasonal practices long before European arrival. The First Fleet established the British settlement at Warrane/Sydney Cove in 1788, and disease, dispossession and frontier violence followed for Aboriginal people. The colony expanded through trade, migration and the 19th-century gold economy, while Circular Quay developed as a central maritime hub. Construction of the Sydney Harbour Bridge in the 20th century and the Opera House after the Second World War reshaped the harbour’s identity. Contemporary interpretation increasingly restores Aboriginal place names, stories and perspectives to a waterfront once presented mainly through its colonial history.",
    wikiTitle: "History of Sydney",
  },
  auckland: {
    summary: "Auckland sits on a landscape long settled by Māori, with volcanic cones and harbours supporting communities well before the colonial city was founded. British authorities established Auckland as the capital of the new colony in 1840, although that role later moved to Wellington. Immigration, shipping and suburban growth turned the isthmus into New Zealand’s largest urban area while Māori history remains fundamental to its identity.",
    more: "Tāmaki Makaurau was prized for fertile volcanic soils, access to two harbours and strategic portage routes, and it supported substantial Māori settlement before European colonisation. The colonial town was established after agreements and land transactions with local iwi, becoming the seat of government until 1865. Harbour commerce, migration and later industrial growth expanded Auckland rapidly, especially after the Second World War. The city’s population became increasingly diverse through Pacific and Asian migration. Mount Eden/Maungawhau, the waterfront and Auckland Museum provide different windows onto the layered Māori, colonial and migrant history behind the modern ‘City of Sails’ image.",
    wikiTitle: "History of Auckland",
  },
  tauranga: {
    summary: "Tauranga’s harbour and surrounding Bay of Plenty have long been important to Māori communities, with major pā sites and trading routes predating European settlement. Missionaries and traders arrived in the 19th century, and the area became a significant battleground during the New Zealand Wars. The modern Port of Tauranga later grew into one of the country’s busiest commercial ports and the cruise gateway for Rotorua.",
    more: "Māori settlement around Tauranga Moana developed around productive coastal resources and defensible volcanic terrain. Mission stations established contact and commerce in the early colonial period, but land pressures and conflict led to the Battles of Gate Pā and Te Ranga in 1864, events with lasting significance for local iwi and New Zealand history. The town expanded gradually through agriculture, rail and port development. Mount Maunganui evolved from a separate seaside community into part of the wider urban area, while the commercial harbour became a major export gateway. Cruise visitors often travel inland to Rotorua, but Tauranga’s own history is deeply tied to Māori land, harbour access and the consequences of 19th-century colonisation.",
    wikiTitle: "Tauranga",
  },
  dubai: {
    summary: "Dubai grew from a Gulf trading and fishing settlement into a regional commercial centre long before its modern skyline appeared. Pearling, creek trade and merchant networks drove the town’s economy, while the 20th-century decline of natural pearls forced new strategies. Oil revenues helped accelerate infrastructure from the late 1960s, but ports, aviation, trade and tourism—not oil alone—built the diversified city visitors see today.",
    more: "Settlement around Dubai Creek benefited from access to regional markets and from rulers who encouraged merchants and low trade barriers. Pearling supported many Gulf communities until cultured pearls and the global depression undermined the industry in the early 20th century. Dubai responded by strengthening re-export trade, expanding the creek and later building major infrastructure such as Port Rashid and Jebel Ali. Oil discovered in the 1960s provided capital but was never as abundant as in neighbouring Abu Dhabi. The city then invested heavily in logistics, real estate, aviation and tourism, transforming a low-rise creek settlement into a global hub while preserving fragments of older neighbourhoods around Al Fahidi and Deira.",
    wikiTitle: "History of Dubai",
  },
  "abu-dhabi": {
    summary: "Abu Dhabi developed from a coastal settlement tied to fishing, pearling and tribal networks into the capital of the United Arab Emirates. The discovery and export of oil in the 20th century transformed the city’s scale, infrastructure and political influence. Yet the old relationship with sea, oasis and desert still shapes how Emirati heritage is presented alongside the modern skyline.",
    more: "The Bani Yas confederation established a settlement on Abu Dhabi island in the 18th century, and the ruling Al Nahyan family made it an important political centre. Pearling and maritime trade sustained the community until the Gulf pearling economy collapsed in the early 20th century. Commercial oil production from the 1960s generated the resources for rapid urban development under Sheikh Zayed bin Sultan Al Nahyan. When the United Arab Emirates formed in 1971, Abu Dhabi became the federal capital. The city later diversified into finance, culture and tourism, with institutions such as Louvre Abu Dhabi adding a new cultural layer to a place whose recent physical growth has been extraordinarily fast.",
    wikiTitle: "Abu Dhabi",
  },
  muscat: {
    summary: "Muscat has been a strategic harbour on the Arabian Sea for centuries, connecting Oman with East Africa, India and the wider Indian Ocean. Portuguese forces captured and fortified the port in the 16th century before Omani rulers expelled them in the 17th century. The old harbour, forts and Mutrah trading district still reflect a maritime empire whose influence once extended far beyond Oman.",
    more: "Muscat’s sheltered coastal position made it valuable to merchants and naval powers moving between the Persian Gulf and Indian Ocean. The Portuguese occupied the city for more than a century and strengthened forts that still dominate the harbour. After their expulsion, Omani power expanded across parts of East Africa and the western Indian Ocean, with close ties between Muscat and Zanzibar. In the 20th century, modernisation accelerated under Sultan Qaboos from 1970, bringing roads, schools, port development and a larger national administrative role. Unlike some Gulf capitals, Muscat retained a relatively low-rise urban form, allowing the historic harbour and mountain setting to remain visually prominent.",
    wikiTitle: "Muscat",
  },
  "cape-town": {
    summary: "Cape Town stands on land long connected to Khoekhoe and San communities and became a Dutch colonial refreshment station in 1652. The settlement expanded through slavery, dispossession and maritime trade before passing to British control and later becoming central to South Africa’s political history. Robben Island, District Six and the waterfront all reveal different sides of a city shaped by colonialism, apartheid and democratic transition.",
    more: "The Dutch East India Company established a station at Table Bay to supply ships travelling between Europe and Asia, importing enslaved people from Africa and Asia and pushing colonial settlement into Indigenous lands. British control followed around the turn of the 19th century, and the port grew with regional trade and mineral-driven expansion inland. Under apartheid, forced removals reshaped neighbourhoods such as District Six, while Robben Island became internationally associated with political imprisonment and resistance. Nelson Mandela’s release and South Africa’s democratic transition transformed the city’s global symbolism. The V&A Waterfront occupies a working harbour landscape whose commercial success should be read alongside those deeper and often painful histories.",
    wikiTitle: "History of Cape Town",
  },
  "port-louis": {
    summary: "Port Louis grew under French rule in the 18th century as a strategic Indian Ocean harbour and later became the capital of British Mauritius. Trade, migration and plantation wealth made the port a meeting point for African, Indian, Chinese and European communities. The modern waterfront sits beside markets, colonial buildings and the Aapravasi Ghat, a UNESCO site central to the history of indentured labour.",
    more: "The French developed Port Louis as a naval and commercial base because of its protected harbour and position on Indian Ocean routes. Britain took Mauritius during the Napoleonic Wars but retained many French cultural and legal influences. After the abolition of slavery, hundreds of thousands of indentured labourers—many from India—passed through the immigration depot now known as Aapravasi Ghat, profoundly shaping Mauritian society. Port activity, sugar exports and later manufacturing and services sustained the capital’s growth. The Central Market, Caudan Waterfront and surviving colonial streets therefore sit within a city whose diversity was produced by successive systems of empire, migration and labour.",
    wikiTitle: "Port Louis",
  },
  "buenos-aires": {
    summary: "Buenos Aires began as a Spanish colonial settlement on the Río de la Plata and grew into the commercial and political centre of Argentina. Its port drove immigration and export wealth in the late 19th and early 20th centuries, bringing millions of newcomers and reshaping neighbourhoods, language and culture. Tango, grand avenues and docklands all emerged from that period of extraordinary urban expansion.",
    more: "A first Spanish settlement in the 16th century failed, while the permanent city founded in 1580 gradually gained importance through Atlantic trade. Buenos Aires became capital of the Viceroyalty of the Río de la Plata in 1776 and played a central role in the independence movement that followed. In the late 1800s, beef and grain exports financed rapid growth and European immigration on a massive scale. The old port areas of La Boca and later Puerto Madero reflect successive stages of maritime development. Political conflict, military rule and the return of democracy also shaped the modern capital, whose cafes, theatres and public spaces carry both elite and working-class histories.",
    wikiTitle: "History of Buenos Aires",
  },
  "rio-de-janeiro": {
    summary: "Rio de Janeiro was founded by the Portuguese in the 16th century and became one of the most important ports in the South Atlantic. Gold, coffee, slavery and imperial government brought immense wealth and inequality, and the city served as Brazil’s capital until Brasília replaced it in 1960. Its mountains, beaches and monumental landmarks now define the visitor image, but the port and historic centre reveal a much deeper colonial and Afro-Brazilian history.",
    more: "Rio grew strategically around Guanabara Bay and became the principal outlet for mineral wealth from the Brazilian interior. The Portuguese royal court relocated here in 1808, an extraordinary event that turned a colonial city into the seat of a European monarchy and accelerated institutional development. After Brazilian independence, Rio remained the imperial and then republican capital. Enslaved Africans and their descendants were fundamental to the city’s economy and culture, and the Valongo Wharf area records one of the largest points of arrival for enslaved people in the Americas. Urban reforms, favelas, samba culture and 20th-century beach development created the complex modern metropolis beyond postcard landmarks such as Sugarloaf and Christ the Redeemer.",
    wikiTitle: "History of Rio de Janeiro",
  },
  ushuaia: {
    summary: "Ushuaia stands in Tierra del Fuego, a region inhabited by Indigenous peoples such as the Yaghan long before Argentine settlement. A mission and later a penal colony helped establish the modern town, whose remote location was deliberately used by the state to strengthen occupation of the far south. Tourism, Antarctic logistics and the Beagle Channel now dominate a city once defined by prison and frontier settlement.",
    more: "Yaghan communities lived by the channels of Tierra del Fuego for generations, adapting to a cold maritime environment before European disease and colonisation devastated their population. Anglican missionaries established a presence in the 19th century, and Argentina later created an official settlement and naval presence. The national prison opened in the early 20th century and brought inmates, guards and infrastructure to the remote town until it closed in 1947. Industrial incentives and migration later increased the population dramatically. Today Ushuaia markets itself as a gateway to Antarctica and the ‘end of the world’, but museums and local Indigenous interpretation add important context to a landscape that was never empty before the frontier city arrived.",
    wikiTitle: "Ushuaia",
  },
};

const wikiUrl = (title: string) => `https://en.wikipedia.org/wiki/${encodeURIComponent(title.replaceAll(" ", "_"))}`;

export function getPortHistory(slug: string): (PortHistory & { wikipediaUrl: string }) | undefined {
  const history = portHistories[slug];
  return history ? { ...history, wikipediaUrl: wikiUrl(history.wikiTitle) } : undefined;
}
